# Use an official Visual Studio Code (VS Code) image as the base image
FROM codercom/code-server

# Set the working directory
WORKDIR /workspace

# Start VS Code
CMD ["code-server", "--auth=none", "--port=8080", "--host=0.0.0.0"]